# Generated by Django 2.1.11 on 2020-08-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='name',
            new_name='devicename',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='state',
            new_name='devicestate',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='system',
            new_name='devicesystem',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='version',
            new_name='deviceversion',
        ),
    ]
